---
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/aelsabbahy/test_travis
  docker:
    - image: golang:1.8.0
  steps:
    - checkout
    - run:
      name: hello world
      command: echo "hello world"
