---
version: 2
jobs:
  build:
    docker:
      - image: golang:1.8.0
    working_directory: /go/src/github.com/aelsabbahy/test_travis
    steps:
      - checkout
      - restore_cache:
          key: test_travis-{{ .Branch }}
      - run: go get github.com/urfave/cli
      - run: go build .
      - run: go test .
      - save_cache:
          key: test_travis-{{ .Branch }}
          paths:
            - /go/src/github.com/aelsabbahy/test_travis/vendor
